python3 convert_to_eraser.py -p best_model_json/bestModel_birnn_2_class_women_majority_all.json -s Data/Evaluation/Model_Eval/majority_all
python3 convert_to_eraser.py -p best_model_json/bestModel_birnn_2_class_women_minority_all.json -s Data/Evaluation/Model_Eval/minority_all
python3 convert_to_eraser.py -p best_model_json/bestModel_birnn_2_class_women_majority_pure.json -s Data/Evaluation/Model_Eval/majority_pure
python3 convert_to_eraser.py -p best_model_json/bestModel_birnn_2_class_women_minority_pure.json -s Data/Evaluation/Model_Eval/minority_pure

python3 convert_to_eraser.py -p best_model_json/bestModel_bert_base_uncased_Attn_train_TRUE_2_class_women_majority_all.json -s Data/Evaluation/Model_Eval/bert_majority_all -b
python3 convert_to_eraser.py -p best_model_json/bestModel_bert_base_uncased_Attn_train_TRUE_2_class_women_minority_all.json -s Data/Evaluation/Model_Eval/bert_minority_all -b
python3 convert_to_eraser.py -p best_model_json/bestModel_bert_base_uncased_Attn_train_TRUE_2_class_women_majority_pure.json -s Data/Evaluation/Model_Eval/bert_majority_pure -b
python3 convert_to_eraser.py -p best_model_json/bestModel_bert_base_uncased_Attn_train_TRUE_2_class_women_minority_pure.json -s Data/Evaluation/Model_Eval/bert_minority_pure -b

cd eraserbenchmark

//lime

python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/majority_all --results ../explanations_dicts/bestModel_birnn_2_class_women_majority_all_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_birnn_majority_all_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/minority_all --results ../explanations_dicts/bestModel_birnn_2_class_women_minority_all_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_birnn_minority_all_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/majority_pure --results ../explanations_dicts/bestModel_birnn_2_class_women_majority_pure_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_birnn_majority_pure_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/minority_pure --results ../explanations_dicts/bestModel_birnn_2_class_women_minority_pure_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_birnn_minority_pure_lime.json

python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/majority_all --results ../explanations_dicts/bestModel_birnnatt_2_class_women_majority_all_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_birnnatt_majority_all_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/minority_all --results ../explanations_dicts/bestModel_birnnatt_2_class_women_minority_all_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_birnnatt_minority_all_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/majority_pure --results ../explanations_dicts/bestModel_birnnatt_2_class_women_majority_pure_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_birnnatt_majority_pure_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/minority_pure --results ../explanations_dicts/bestModel_birnnatt_2_class_women_minority_pure_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_birnnatt_minority_pure_lime.json

python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/majority_all --results ../explanations_dicts/bestModel_birnnscrat_2_class_women_majority_all_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_birnnscrat_majority_all_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/minority_all --results ../explanations_dicts/bestModel_birnnscrat_2_class_women_minority_all_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_birnnscrat_minority_all_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/majority_pure --results ../explanations_dicts/bestModel_birnnscrat_2_class_women_majority_pure_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_birnnscrat_majority_pure_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/minority_pure --results ../explanations_dicts/bestModel_birnnscrat_2_class_women_minority_pure_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_birnnscrat_minority_pure_lime.json

python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/majority_all --results ../explanations_dicts/bestModel_cnn_gru_2_class_women_majority_all_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_cnn_gru_majority_all_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/minority_all --results ../explanations_dicts/bestModel_cnn_gru_2_class_women_minority_all_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_cnn_gru_minority_all_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/majority_pure --results ../explanations_dicts/bestModel_cnn_gru_2_class_women_majority_pure_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_cnn_gru_majority_pure_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/minority_pure --results ../explanations_dicts/bestModel_cnn_gru_2_class_women_minority_pure_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_cnn_gru_minority_pure_lime.json

python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_majority_all --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_TRUE_2_class_women_majority_all_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_bert_true_majority_all_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_minority_all --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_TRUE_2_class_women_minority_all_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_bert_true_minority_all_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_majority_pure --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_TRUE_2_class_women_majority_pure_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_bert_true_majority_pure_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_minority_pure --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_TRUE_2_class_women_minority_pure_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_bert_true_minority_pure_lime.json

python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_majority_all --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_FALSE_2_class_women_majority_all_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_bert_false_majority_all_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_minority_all --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_FALSE_2_class_women_minority_all_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_bert_false_minority_all_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_majority_pure --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_FALSE_2_class_women_majority_pure_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_bert_false_majority_pure_lime.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_minority_pure --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_FALSE_2_class_women_minority_pure_explanation_with_lime_100_1.0.json --score_file ../model_explain_output_bert_false_minority_pure_lime.json


//rationale

python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/majority_all --results ../explanations_dicts/bestModel_birnnatt_2_class_women_majority_all_1.0_explanation_top5.json --score_file ../model_explain_output_birnnatt_majority_all_rationale.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/minority_all --results ../explanations_dicts/bestModel_birnnatt_2_class_women_minority_all_1.0_explanation_top5.json --score_file ../model_explain_output_birnnatt_minority_all_rationale.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/majority_pure --results ../explanations_dicts/bestModel_birnnatt_2_class_women_majority_pure_1.0_explanation_top5.json --score_file ../model_explain_output_birnnatt_majority_pure_rationale.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/minority_pure --results ../explanations_dicts/bestModel_birnnatt_2_class_women_minority_pure_1.0_explanation_top5.json --score_file ../model_explain_output_birnnatt_minority_pure_rationale.json

python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_majority_all --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_TRUE_2_class_women_majority_all_0.001_explanation_top5.json --score_file ../model_explain_output_bert_true_majority_all_rationale.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_minority_all --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_TRUE_2_class_women_minority_all_0.001_explanation_top5.json --score_file ../model_explain_output_bert_true_minority_all_rationale.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_majority_pure --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_TRUE_2_class_women_majority_pure_0.001_explanation_top5.json --score_file ../model_explain_output_bert_true_majority_pure_rationale.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_minority_pure --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_TRUE_2_class_women_minority_pure_0.001_explanation_top5.json --score_file ../model_explain_output_bert_true_minority_pure_rationale.json

python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_majority_all --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_FALSE_2_class_women_majority_all_0.001_explanation_top5.json --score_file ../model_explain_output_bert_false_majority_all_rationale.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_minority_all --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_FALSE_2_class_women_minority_all_0.001_explanation_top5.json --score_file ../model_explain_output_bert_false_minority_all_rationale.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_majority_pure --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_FALSE_2_class_women_majority_pure_0.001_explanation_top5.json --score_file ../model_explain_output_bert_false_majority_pure_rationale.json
python3 rationale_benchmark/metrics.py --split test --strict --data_dir ../Data/Evaluation/Model_Eval/bert_minority_pure --results ../explanations_dicts/bestModel_bert_base_uncased_Attn_train_FALSE_2_class_women_minority_pure_0.001_explanation_top5.json --score_file ../model_explain_output_bert_false_minority_pure_rationale.json

